// Source-level cost data by capability
// Generated by scripts/importSourceCosts.ts on 2026-02-02T16:37:51.893Z
// DO NOT EDIT MANUALLY - regenerate using: npm run import-source-costs

import { SourceCostDataset } from '../types/sourceCosts';

export const sourceCostData: SourceCostDataset = {
  "metadata": {
    "importDate": "2026-02-02T16:37:51.886Z",
    "dataSource": "C:\\Users\\MICHAEL.BUTTERLY\\SourceCode\\heatmap\\src\\input_docs\\fake_costs.csv",
    "period": "2026-02",
    "currency": "USD",
    "totalCost": 38119705,
    "capabilityCount": 12,
    "sourceCount": 7
  },
  "costs": {
    "Actuarial Valuation & Modelling": {
      "AU": {
        "cost": 938000,
        "confidence": "actual"
      },
      "DE": {
        "cost": 3603600,
        "confidence": "actual"
      },
      "CH": {
        "cost": 561960,
        "confidence": "actual"
      },
      "UK": {
        "cost": 469262,
        "confidence": "actual"
      },
      "ZNA": {
        "cost": 728846,
        "confidence": "actual"
      }
    },
    "Billing & Payments": {
      "BR": {
        "cost": 201243,
        "confidence": "actual"
      },
      "CH": {
        "cost": 243180,
        "confidence": "actual"
      },
      "UK": {
        "cost": 80640,
        "confidence": "actual"
      },
      "ZNA": {
        "cost": 3872963,
        "confidence": "actual"
      }
    },
    "Analytics & BI": {
      "AU": {
        "cost": 73700,
        "confidence": "actual"
      },
      "BR": {
        "cost": 138371,
        "confidence": "actual"
      },
      "IT": {
        "cost": 1067099,
        "confidence": "actual"
      },
      "CH": {
        "cost": 259560,
        "confidence": "actual"
      },
      "ZNA": {
        "cost": 1953481,
        "confidence": "actual"
      }
    },
    "Data Management": {
      "AU": {
        "cost": 737000,
        "confidence": "actual"
      },
      "CH": {
        "cost": 279720,
        "confidence": "actual"
      }
    },
    "Financial Accounting & Close": {
      "BR": {
        "cost": 39264,
        "confidence": "actual"
      },
      "DE": {
        "cost": 15561,
        "confidence": "actual"
      },
      "CH": {
        "cost": 35280,
        "confidence": "actual"
      },
      "UK": {
        "cost": 160890,
        "confidence": "actual"
      },
      "ZNA": {
        "cost": 11910076,
        "confidence": "actual"
      }
    },
    "Investment Management": {
      "AU": {
        "cost": 1675000,
        "confidence": "actual"
      }
    },
    "Planning, Performance & Management (PPM)": {
      "AU": {
        "cost": 123950,
        "confidence": "actual"
      },
      "DE": {
        "cost": 546728,
        "confidence": "actual"
      },
      "CH": {
        "cost": 350280,
        "confidence": "actual"
      },
      "UK": {
        "cost": 328483,
        "confidence": "actual"
      },
      "ZNA": {
        "cost": 8432,
        "confidence": "actual"
      }
    },
    "Regulatory & Statutory Reporting": {
      "AU": {
        "cost": 23450,
        "confidence": "actual"
      },
      "BR": {
        "cost": 319299,
        "confidence": "actual"
      },
      "DE": {
        "cost": 85176,
        "confidence": "actual"
      },
      "UK": {
        "cost": 345720,
        "confidence": "actual"
      },
      "ZNA": {
        "cost": 29785,
        "confidence": "actual"
      }
    },
    "Reinsurance Management": {
      "DE": {
        "cost": 91913,
        "confidence": "actual"
      },
      "IT": {
        "cost": 106735,
        "confidence": "actual"
      },
      "ZNA": {
        "cost": 483520,
        "confidence": "actual"
      }
    },
    "Tax Management": {
      "BR": {
        "cost": 12965,
        "confidence": "actual"
      },
      "DE": {
        "cost": 129687,
        "confidence": "actual"
      },
      "ZNA": {
        "cost": 407128,
        "confidence": "actual"
      }
    },
    "Technical Accounting / Subledger": {
      "AU": {
        "cost": 1474000,
        "confidence": "actual"
      },
      "IT": {
        "cost": 3485524,
        "confidence": "actual"
      }
    },
    "Treasury & Liquidity Management": {
      "DE": {
        "cost": 90090,
        "confidence": "actual"
      },
      "IT": {
        "cost": 478179,
        "confidence": "actual"
      },
      "CH": {
        "cost": 81900,
        "confidence": "actual"
      },
      "ZNA": {
        "cost": 72065,
        "confidence": "actual"
      }
    }
  }
};
